import * as path from 'node:path'
import * as fs from 'node:fs'
import { app } from 'electron'
import { getDb } from './db'
import type { GhosttyUserConfig } from '../shared/types'

const GHOSTTY_CONFIG_HEADER = '# Generated by Orpheus — do not edit by hand.\n'

/**
 * Parse the ghostty_config_json column from the singleton claude_global_settings row.
 * Falls back to the empty default on any parse error.
 */
export function getGhosttyUserConfig(): GhosttyUserConfig {
  const db = getDb()
  const row = db
    .prepare('SELECT ghostty_config_json FROM claude_global_settings WHERE id = 1')
    .get() as { ghostty_config_json: string } | undefined
  if (!row) return { settings: {}, keybinds: [] }
  try {
    const parsed = JSON.parse(row.ghostty_config_json)
    return {
      settings: parsed.settings && typeof parsed.settings === 'object' ? parsed.settings : {},
      keybinds: Array.isArray(parsed.keybinds) ? parsed.keybinds : []
    }
  } catch {
    return { settings: {}, keybinds: [] }
  }
}

/**
 * Merge patch over current config (replace-semantics: caller sends full objects).
 * Persists to DB and returns the merged value.
 */
export function updateGhosttyUserConfig(patch: Partial<GhosttyUserConfig>): GhosttyUserConfig {
  const current = getGhosttyUserConfig()
  const merged: GhosttyUserConfig = {
    settings: patch.settings !== undefined ? patch.settings : current.settings,
    keybinds: patch.keybinds !== undefined ? patch.keybinds : current.keybinds
  }
  const db = getDb()
  db.prepare('UPDATE claude_global_settings SET ghostty_config_json = ? WHERE id = 1').run(
    JSON.stringify(merged)
  )
  return merged
}

/**
 * Serialize a GhosttyUserConfig into ghostty config-file text.
 * Format: `key = value` lines (unquoted). Keybinds: `keybind = trigger=action`.
 */
export function serializeGhosttyConfig(cfg: GhosttyUserConfig): string {
  const lines: string[] = [GHOSTTY_CONFIG_HEADER]
  for (const [key, value] of Object.entries(cfg.settings)) {
    if (typeof value === 'boolean') {
      lines.push(`${key} = ${value ? 'true' : 'false'}`)
    } else {
      lines.push(`${key} = ${value}`)
    }
  }
  for (const kb of cfg.keybinds) {
    lines.push(`keybind = ${kb.trigger}=${kb.action}`)
  }
  return lines.join('\n') + '\n'
}

/**
 * Write the current ghostty user config to userData/ghostty-user.conf.
 * Returns the absolute path. Idempotent — safe to call on every terminal mount.
 */
export function writeGhosttyConfigFile(): string {
  const configPath = path.join(app.getPath('userData'), 'ghostty-user.conf')
  const cfg = getGhosttyUserConfig()
  const content = serializeGhosttyConfig(cfg)
  fs.writeFileSync(configPath, content, 'utf8')
  return configPath
}
