// ---------------------------------------------------------------------------
// src/main/routingProxy/config.ts
//
// Generates the CLIProxyAPI config.yaml written into
// userData/routing-proxy/<version>/config.yaml. Minimal working config per
// the unit spec: host, port, auth-dir, debug. The auth dir is passed in
// explicitly by the caller (manager.ts, via paths.authDir()) rather than
// derived internally here — keeps this module electron-free so
// scripts/verify-routing-proxy.ts can exercise it fully offline.
//
// THE MANAGEMENT SECRET NEVER GOES IN THIS FILE. MANAGEMENT_PASSWORD is
// supplied to the child process purely via env (see lifecycle.ts) so the
// management API is usable without a plaintext secret ever touching disk —
// see the "no MANAGEMENT_PASSWORD/secret key in config.yaml" assertion in
// scripts/verify-routing-proxy.ts.
// ---------------------------------------------------------------------------

import * as fs from 'node:fs/promises'

export interface RoutingProxyConfigOptions {
  host: string
  port: number
  authDir: string
  debug?: boolean
}

/**
 * Render config.yaml text. Pure/no I/O so it's directly assertable in the
 * offline harness (host/port/auth-dir present, no hardcoded absolute path
 * baked in beyond what the caller explicitly passed via authDir, no secret
 * key present).
 */
export function renderRoutingProxyConfig(options: RoutingProxyConfigOptions): string {
  const lines = [
    '# Generated by Orpheus — do not edit by hand.',
    `host: ${options.host}`,
    `port: ${options.port}`,
    `auth-dir: ${options.authDir}`,
    `debug: ${options.debug ? 'true' : 'false'}`,
    ''
  ]
  return lines.join('\n')
}

export interface WriteConfigOptions {
  host: string
  port: number
  /** Caller-supplied auth-dir (manager.ts passes paths.authDir()) — never
   *  derived internally so this module has no electron dependency. */
  authDir: string
  debug?: boolean
}

/**
 * Build config options + write config.yaml to `configPath`. `options.authDir`
 * is caller-supplied (never hardcoded — manager.ts derives it from
 * app.getPath('userData') via paths.authDir()). Returns the rendered text
 * (mainly for tests/logging — never log it if it ever grows a secret field,
 * though today it holds none).
 */
export async function writeRoutingProxyConfig(
  configFilePath: string,
  options: WriteConfigOptions
): Promise<string> {
  await fs.mkdir(options.authDir, { recursive: true })
  const text = renderRoutingProxyConfig({
    host: options.host,
    port: options.port,
    authDir: options.authDir,
    debug: options.debug ?? false
  })
  await fs.writeFile(configFilePath, text, 'utf8')
  return text
}
